site_name: "basic_OASIS"
site_description: "Minimal project website"
site_url: "https://cu-esiil.github.io/basic_OASIS/"

repo_name: "CU-ESIIL/basic_OASIS"
repo_url: "https://github.com/CU-ESIIL/basic_OASIS"
edit_uri: "edit/main/docs/"

nav:
  - Site:
      - Home: index.md

theme:
  name: mkdocs

extra_css:
  - stylesheets/extra.css

plugins:
  - search
